import type { AIModel } from './types';

export const aiModels: AIModel[] = [
  {
    id: 'kling-1.6',
    name: 'Kling 1.6',
    provider: 'Kuaishou',
    descriptionKey: 'kling16Desc',
    image: '/images/models/kling.jpg',
    href: '/create/text-to-video?model=kling-1.6',
    badge: 'popular',
    features: ['high-quality', 'fast', 'realistic'],
  },
  {
    id: 'runway-gen3',
    name: 'Runway Gen-3',
    provider: 'Runway',
    descriptionKey: 'runwayGen3Desc',
    image: '/images/models/runway.jpg',
    href: '/create/text-to-video?model=runway-gen3',
    isNew: true,
    features: ['cinematic', 'creative', 'professional'],
  },
  {
    id: 'pika-1.5',
    name: 'Pika 1.5',
    provider: 'Pika Labs',
    descriptionKey: 'pika15Desc',
    image: '/images/models/pika.jpg',
    href: '/create/text-to-video?model=pika-1.5',
    features: ['stylized', 'creative', 'fast'],
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    provider: 'MiniMax',
    descriptionKey: 'minimaxDesc',
    image: '/images/models/minimax.jpg',
    href: '/create/text-to-video?model=minimax',
    features: ['anime', 'cartoon', 'creative'],
  },
  {
    id: 'luma-dream',
    name: 'Luma Dream Machine',
    provider: 'Luma AI',
    descriptionKey: 'lumaDreamDesc',
    image: '/images/models/luma.jpg',
    href: '/create/text-to-video?model=luma-dream',
    features: ['3d', 'realistic', 'smooth'],
  },
  {
    id: 'hailuo',
    name: 'Hailuo AI',
    provider: 'MiniMax',
    descriptionKey: 'hailuoDesc',
    image: '/images/models/hailuo.jpg',
    href: '/create/text-to-video?model=hailuo',
    isNew: true,
    features: ['chinese-style', 'artistic', 'creative'],
  },
  {
    id: 'cogvideox',
    name: 'CogVideoX',
    provider: 'Zhipu AI',
    descriptionKey: 'cogvideoxDesc',
    image: '/images/models/cogvideox.jpg',
    href: '/create/text-to-video?model=cogvideox',
    features: ['open-source', 'customizable', 'research'],
  },
  {
    id: 'stable-video',
    name: 'Stable Video Diffusion',
    provider: 'Stability AI',
    descriptionKey: 'stableVideoDesc',
    image: '/images/models/stable-video.jpg',
    href: '/create/image-to-video?model=stable-video',
    features: ['image-to-video', 'stable', 'consistent'],
  },
];
