import type { AIModel } from './types';

export const aiModels: AIModel[] = [
  {
    id: 'veo-3',
    name: 'Veo 3',
    provider: 'Google',
    descriptionKey: 'veo3Desc',
    image: '/images/models/veo.svg',
    href: '/models/veo-3',
    badge: 'popular',
    isNew: true,
    features: ['audio', 'cinematic', '4K'],
  },
  {
    id: 'sora-2',
    name: 'Sora 2',
    provider: 'OpenAI',
    descriptionKey: 'sora2Desc',
    image: '/images/models/sora.svg',
    href: '/models/sora-2',
    badge: 'popular',
    isNew: true,
    features: ['physics', 'cinematic', 'multi-shot'],
  },
  {
    id: 'kling',
    name: 'Kling AI',
    provider: 'Kuaishou',
    descriptionKey: 'klingDesc',
    image: '/images/models/kling.svg',
    href: '/models/kling',
    badge: 'popular',
    features: ['high-quality', 'lip-sync', 'motion-brush'],
  },
  {
    id: 'hailuo',
    name: 'Hailuo AI',
    provider: 'MiniMax',
    descriptionKey: 'hailuoDesc',
    image: '/images/models/hailuo.svg',
    href: '/models/hailuo',
    badge: 'popular',
    features: ['fast', 'camera-control', 'creative'],
  },
  {
    id: 'seedance',
    name: 'Seedance',
    provider: 'ByteDance',
    descriptionKey: 'seedanceDesc',
    image: '/images/models/seedance.svg',
    href: '/models/seedance',
    isNew: true,
    features: ['semantic', 'multi-shot', 'multi-style'],
  },
  {
    id: 'wan',
    name: 'Wan AI',
    provider: 'Alibaba',
    descriptionKey: 'wanDesc',
    image: '/images/models/wan.svg',
    href: '/models/wan',
    isNew: true,
    features: ['open-source', '100-styles', '14B-params'],
  },
];
