import type { VideoTool } from './types';

export const videoTools: VideoTool[] = [
  {
    id: 'image-to-video',
    titleKey: 'imageToVideo',
    descriptionKey: 'imageToVideoDesc',
    icon: 'Film',
    href: '/create/image-to-video',
    gradient: 'from-purple-500 to-pink-500',
    badge: 'hot',
  },
  {
    id: 'text-to-video',
    titleKey: 'textToVideo',
    descriptionKey: 'textToVideoDesc',
    icon: 'Type',
    href: '/create/text-to-video',
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'reference-to-video',
    titleKey: 'referenceToVideo',
    descriptionKey: 'referenceToVideoDesc',
    icon: 'Sparkles',
    href: '/create/reference-to-video',
    gradient: 'from-orange-500 to-yellow-500',
    isNew: true,
  },
  {
    id: 'video-extend',
    titleKey: 'videoExtend',
    descriptionKey: 'videoExtendDesc',
    icon: 'Maximize2',
    href: '/create/extend',
    gradient: 'from-green-500 to-emerald-500',
  },
  {
    id: 'video-upscale',
    titleKey: 'videoUpscale',
    descriptionKey: 'videoUpscaleDesc',
    icon: 'ZoomIn',
    href: '/create/upscale',
    gradient: 'from-indigo-500 to-purple-500',
    isPro: true,
  },
  {
    id: 'lip-sync',
    titleKey: 'lipSync',
    descriptionKey: 'lipSyncDesc',
    icon: 'Mic',
    href: '/create/lip-sync',
    gradient: 'from-rose-500 to-pink-500',
    isNew: true,
  },
  {
    id: 'video-effects',
    titleKey: 'videoEffects',
    descriptionKey: 'videoEffectsDesc',
    icon: 'Wand2',
    href: '/create/effects',
    gradient: 'from-amber-500 to-orange-500',
  },
  {
    id: 'background-remove',
    titleKey: 'backgroundRemove',
    descriptionKey: 'backgroundRemoveDesc',
    icon: 'Eraser',
    href: '/create/background-remove',
    gradient: 'from-teal-500 to-cyan-500',
  },
];
